services:
  - docker
language: go
go: "1.12.x"

env:
  global:
    - GO111MODULE=on

before_install:
  - node --version
install: make setup
script:
  - make test-ci
  - cd website && npm install && npm run build && cd ..

before_deploy:
  - docker login docker.io -u $DOCKER_USER -p $DOCKER_PASSWORD
  - echo "machine github.com login ${GITHUB_USER} password ${GITHUB_TOKEN}" > ~/.netrc

deploy:
  - provider: script
    script: docker run --rm --privileged -v $(pwd):/darkroom -v /var/run/docker.sock:/var/run/docker.sock -w /darkroom -e GITHUB_TOKEN -e DOCKER_USER -e DOCKER_PASSWORD bepsays/ci-goreleaser goreleaser release --skip-validate --rm-dist
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: cd website && npm install && GIT_USER="${GITHUB_USER}" npm run publish-gh-pages
    on:
      branch: master

notifications:
  email: false
