language: go
go: '1.12.x'

env:
  global:
    - GO111MODULE=on GITHUB_USER=irfn

install: make setup
script:
  - make test-ci
  - cd website && yarn build

before_deploy:
  - docker login docker.io -u $DOCKER_USER -p $DOCKER_PASSWORD
  - echo "machine github.com login ${GITHUB_USER} password ${GITHUB_TOKEN}" > ~/.netrc

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --skip-validate
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: cd website && yarn install && GIT_USER="${GITHUB_USER}" yarn run publish-gh-pages
    on:
      branch: master

notifications:
  email: false
